
/* authentication*/
export const AUTHENTICATE = 'AUTHENTICATE';


/* winebars */
export const FETCH_WINEBARS_FROM_SERVER = 'FETCH_WINEBARS_FROM_SERVER';
export const FETCH_WINEBAR_DETAIL_FROM_SERVER = 'FETCH_WINEBAR_DETAIL_FROM_SERVER';


export const FETCH_WINESELECTION_FROM_SERVER = 'FETCH_WINESELECTION_FROM_SERVER';
export const FETCH_WINE_DETAIL_FROM_SERVER = 'FETCH_WINE_DETAIL_FROM_SERVER';
export const FETCH_TODAY_WINES_FROM_SERVER = 'FETCH_TODAY_WINES_FROM_SERVER';
export const POP_ONE_CARD_FROM_TODAY_WINES = 'POP_ONE_CARD_FROM_TODAY_WINES';