
/* authentication*/
export const AUTHENTICATE = 'AUTHENTICATE';


/* winebars */
export const FETCH_WINEBARS_FROM_SERVER = 'FETCH_WINEBARS_FROM_SERVER';
export const FETCH_WINEBAR_DETAIL_FROM_SERVER = 'FETCH_WINEBAR_DETAIL_FROM_SERVER';


export const FETCH_WINESELECTION_FROM_SERVER = 'FETCH_WINESELECTION_FROM_SERVER';